initial navbar
uclaacm/hackucla.com pull request #7
Opened 2018-05-08 03:46 UTC by punteek

Implemented navbar based on Figma design.

2018-05-08 04:02 UTC, shannonphu requested changes

2018-05-08 04:02 UTC, shannonphu commented on client/src/components/Nav/Nav.jsx
> +import './hack-navbar.css';
Name your CSS files the same as the component, so `Nav.css`

2018-05-08 04:02 UTC, shannonphu commented on client/public/index.html
> +    <script type="text/javascript" src="hack-navbar.js"></script>
You shouldn't need to import external JS files, the React should be able to do anything you want

2018-05-08 04:02 UTC, shannonphu commented on client/src/components/Nav/Nav.jsx
> +						<img id="logo-hack" src={'img/logo-hack.png'} alt="" />
Do we need curly brackets here and the line below? It is just a const string.

2018-05-08 04:02 UTC, shannonphu commented on client/src/components/Nav/Nav.jsx
> +					<div className="ham-menu mobile-only">
You can add a React `onClick` handler here to replace your external JS functionality. And in that handler, set some state for conditional rendering.

2018-05-11 01:55 UTC, punteek commented
Ok, all of the comments should have been addressed.

2018-05-12 01:34 UTC, shannonphu requested changes

2018-05-12 01:34 UTC, shannonphu commented on client/src/components/Nav/Nav.jsx
> +		this.toggleDropdown = this.toggleDropdown.bind(this);
Move these bind statements underneath state initialization.

2018-05-12 01:34 UTC, shannonphu commented on client/src/components/Nav/Nav.jsx
> +		console.log('hello!');
Remove any console.logs used for testing

2018-05-12 01:34 UTC, shannonphu commented on client/src/components/Nav/Nav.jsx
> +		if(this.state.show === false){
Please keep your all your spacing consistent with everything else
```
if () {

}
```

2018-05-12 01:34 UTC, shannonphu commented on client/src/components/Nav/Nav.jsx
> +			styles = {
Don't set styles here. Keep styles in a CSS class and in `render()`, conditionally set the className to whichever class you want it to have depending on the state.

2018-05-12 01:34 UTC, shannonphu commented on client/src/components/Nav/Nav.jsx
> +					<div id="general-logo">
Can you use `className` instead of `id` for all?

2018-05-17 06:56 UTC, shannonphu commented
fixes #9

2018-05-23 01:46 UTC, punteek commented
Updated based on the most recent comments.

2018-05-23 01:55 UTC, TimothyGu commented on client/src/components/Nav/Nav.css
> +* {
This will affect all elements on the page, not just the navbar. Are you sure this is what you want?

2018-05-23 01:55 UTC, TimothyGu commented on client/src/components/Nav/Nav.css
> +	top: 0px;
Inconsistent indentation (tabs vs. spaces).

2018-05-23 19:59 UTC, shannonphu approved these changes

2018-05-23 20:01 UTC, merged